
interval: 7200
ticker: USDT_ETH
auto_trade: true


poloniex  :
  api_secret:
  api_key:
  public_commands:
     - returnTicker
     - return24hVolume
     - returnOrderBook
     - returnMarketTradeHistory
     - returnChartData
     - returnCurrencies
     - returnLoanOrders
  private_commands:
     - returnBalances
     - returnCompleteBalances
     - returnDepositAddresses
     - generateNewAddress
     - returnDepositsWithdrawals
     - returnOpenOrders
     - returnTradeHistory
     - returnOrderTrades
     - buy
     - sell
     - cancelOrder
     - moveOrder
     - withdraw
     - returnFeeInfo
     - returnAvailableAccountBalances
     - returnTradableBalances
     - transferBalance
     - returnMarginAccountSummary
     - marginBuy
     - marginSell
     - getMarginPosition
     - closeMarginPosition
     - createLoanOffer
     - cancelLoanOffer
     - returnOpenLoanOffers
     - returnActiveLoans
     - toggleAutoRenew
  tickers:
     - BTC_BTS
     - BTC_DASH
     - BTC_DOGE
     - BTC_LTC
     - BTC_NXT
     - BTC_STR
     - BTC_XEM
     - BTC_XMR
     - BTC_XRP
     - USDT_BTC
     - USDT_DASH
     - USDT_LTC
     - USDT_STR
     - USDT_XMR
     - USDT_XRP
     - USDT_DOT
     - BTC_ETH
     - USDT_ETH
     - BTC_SC
     - BTC_DCR
     - BTC_LSK
     - BTC_STEEM
     - BTC_ETC
     - ETH_ETC
     - USDT_ETC
     - BTC_REP
     - USDT_REP
     - BTC_ARDR
     - BTC_ZEC
     - ETH_ZEC
     - USDT_ZEC
     - BTC_STRAT
     - BTC_GNT
     - BTC_ZRX
     - ETH_ZRX
     - BTC_CVC
     - BTC_OMG
     - BTC_GAS
     - BTC_STORJ
     - BTC_EOS
     - ETH_EOS
     - USDT_EOS
     - BTC_SNT
     - BTC_KNC
     - BTC_BAT
     - ETH_BAT
     - USDT_BAT
     - BTC_LOOM
     - USDT_DOGE
     - USDT_GNT
     - USDT_LSK
     - USDT_SC
     - USDT_ZRX
     - BTC_QTUM
     - USDT_QTUM
     - USDC_BTC
     - USDC_ETH
     - USDC_USDT
     - BTC_MANA
     - USDT_MANA
     - BTC_BNT
     - BTC_BCHABC
     - USDC_BCHABC
     - BTC_BCHSV
     - USDC_BCHSV
     - USDC_XRP
     - USDC_XMR
     - USDC_STR
     - USDC_DOGE
     - USDC_LTC
     - USDC_ZEC
     - BTC_FOAM
     - BTC_NMR
     - BTC_POLY
     - BTC_LPT
     - USDC_GRIN
     - BTC_ATOM
     - USDC_ATOM
     - USDT_ATOM
     - USDC_DASH
     - USDC_EOS
     - USDC_ETC
     - USDT_BCHSV
     - USDT_BCHABC
     - USDT_GRIN
     - BTC_TRX
     - USDC_TRX
     - USDT_TRX
     - BTC_ETHBNT
     - TRX_ETH
     - TRX_XRP
     - USDT_BTT
     - TRX_BTT
     - USDT_WIN
     - TRX_WIN
     - TRX_STEEM
     - BTC_LINK
     - TRX_LINK
     - BTC_XTZ
     - USDT_XTZ
     - TRX_XTZ
     - USDT_BEAR
     - USDT_BULL
     - USDT_TRXBEAR
     - USDT_TRXBULL
     - PAX_BTC
     - PAX_ETH
     - USDT_PAX
     - USDT_USDJ
     - USDJ_BTC
     - USDJ_TRX
     - BTC_SNX
     - USDT_SNX
     - TRX_SNX
     - USDT_BSVBEAR
     - USDT_BSVBULL
     - BTC_MATIC
     - USDT_MATIC
     - TRX_MATIC
     - USDT_BCHBEAR
     - USDT_BCHBULL
     - USDT_ETHBEAR
     - USDT_ETHBULL
     - BTC_MKR
     - USDT_MKR
     - USDT_BVOL
     - USDT_IBVOL
     - DAI_BTC
     - DAI_ETH
     - USDT_DAI
     - BTC_NEO
     - USDT_NEO
     - TRX_NEO
     - BTC_SWFTC
     - USDT_SWFTC
     - TRX_SWFTC
     - USDT_JST
     - TRX_JST
     - BTC_FXC
     - USDT_FXC
     - TRX_FXC
     - USDT_BCN
     - USDT_STEEM
     - USDT_LINK
     - USDJ_BTT
     - BTC_AVA
     - USDT_AVA
     - TRX_AVA
     - USDT_XRPBULL
     - USDT_XRPBEAR
     - USDT_EOSBULL
     - USDT_EOSBEAR
     - USDT_LINKBULL
     - USDT_LINKBEAR
     - BTC_CHR
     - USDT_CHR
     - TRX_CHR
     - BNB_BTC
     - USDT_BNB
     - USDT_BUSD
     - TRX_BNB
     - BUSD_BNB
     - BUSD_BTC
     - BTC_MDT
     - USDT_MDT
     - TRX_MDT
     - USDT_BCHC
     - USDT_COMP
     - ETH_COMP
     - BTC_XFIL
     - USDT_XFIL
     - USDT_CUSDT
     - BTC_LEND
     - USDT_LEND
     - BTC_REN
     - USDT_REN
     - BTC_LRC
     - USDT_LRC
     - USDT_BAL
     - ETH_BAL
     - BTC_WRX
     - USDT_WRX
     - TRX_WRX
     - USDT_STAKE
     - USDT_BZRX
     - BTC_SXP
     - USDT_SXP
     - TRX_SXP
     - USDT_MTA
     - USDT_YFI
     - BTC_STPT
     - USDT_STPT
     - TRX_STPT
     - USDT_TRUMPWIN
     - USDT_TRUMPLOSE
     - USDT_DEC
     - USDT_PLT
     - USDT_UMA
     - USDT_KTON
     - USDT_RING
     - BTC_SWAP
     - USDT_SWAP
     - USDT_TEND
     - BTC_EXE
     - USDT_EXE
     - USDT_TRADE
     - USDT_GEEQ
     - USDT_BAND
     - USDT_DOS
     - USDT_DIA
     - USDT_ZAP
  intervals:
    - 300
    - 900
    - 1800
    - 7200
    - 14400
    - 8640
  currencies:
     - 1CR
     - ABY
     - AC
     - ACH
     - ADN
     - AEON
     - AERO
     - AIR
     - APH
     - AUR
     - AXIS
     - BALLS
     - BANK
     - BBL
     - BBR
     - BCC
     - BCN
     - BDC
     - BDG
     - BELA
     - BITS
     - BLK
     - BLOCK
     - BLU
     - BNS
     - BONES
     - BOST
     - BTC
     - BTCD
     - BTCS
     - BTM
     - BTS
     - BURN
     - BURST
     - C2
     - CACH
     - CAI
     - CC
     - CCN
     - CGA
     - CHA
     - CINNI
     - CLAM
     - CNL
     - CNMT
     - CNOTE
     - COMM
     - CON
     - CORG
     - CRYPT
     - CURE
     - CYC
     - DGB
     - DICE
     - DIEM
     - DIME
     - DIS
     - DNS
     - DOGE
     - DASH
     - DRKC
     - DRM
     - DSH
     - DVK
     - EAC
     - EBT
     - ECC
     - EFL
     - EMC2
     - EMO
     - ENC
     - eTOK
     - EXE
     - FAC
     - FCN
     - FIBRE
     - FLAP
     - FLDC
     - FLT
     - FOX
     - FRAC
     - FRK
     - FRQ
     - FVZ
     - FZ
     - FZN
     - GAP
     - GDN
     - GEMZ
     - GEO
     - GIAR
     - GLB
     - GAME
     - GML
     - GNS
     - GOLD
     - GPC
     - GPUC
     - GRCX
     - GRS
     - GUE
     - H2O
     - HIRO
     - HOT
     - HUC
     - HVC
     - HYP
     - HZ
     - IFC
     - ITC
     - IXC
     - JLH
     - JPC
     - JUG
     - KDC
     - KEY
     - LC
     - LCL
     - LEAF
     - LGC
     - LOL
     - LOVE
     - LQD
     - LTBC
     - LTC
     - LTCX
     - MAID
     - MAST
     - MAX
     - MCN
     - MEC
     - METH
     - MIL
     - MIN
     - MINT
     - MMC
     - MMNXT
     - MMXIV
     - MNTA
     - MON
     - MRC
     - MRS
     - OMNI
     - MTS
     - MUN
     - MYR
     - MZC
     - N5X
     - NAS
     - NAUT
     - NAV
     - NBT
     - NEOS
     - NL
     - NMC
     - NOBL
     - NOTE
     - NOXT
     - NRS
     - NSR
     - NTX
     - NXT
     - NXTI
     - OPAL
     - PAND
     - PAWN
     - PIGGY
     - PINK
     - PLX
     - PMC
     - POT
     - PPC
     - PRC
     - PRT
     - PTS
     - Q2C
     - QBK
     - QCN
     - QORA
     - QTL
     - RBY
     - RDD
     - RIC
     - RZR
     - SDC
     - SHIBE
     - SHOPX
     - SILK
     - SJCX
     - SLR
     - SMC
     - SOC
     - SPA
     - SQL
     - SRCC
     - SRG
     - SSD
     - STR
     - SUM
     - SUN
     - SWARM
     - SXC
     - SYNC
     - SYS
     - TAC
     - TOR
     - TRUST
     - TWE
     - UIS
     - ULTC
     - UNITY
     - URO
     - USDE
     - USDT
     - UTC
     - UTIL
     - UVC
     - VIA
     - VOOT
     - VRC
     - VTC
     - WC
     - WDC
     - WIKI
     - WOLF
     - X13
     - XAI
     - XAP
     - XBC
     - XC
     - XCH
     - XCN
     - XCP
     - XCR
     - XDN
     - XDP
     - XHC
     - XLB
     - XMG
     - XMR
     - XPB
     - XPM
     - XRP
     - XSI
     - XST
     - XSV
     - XUSD
     - XXC
     - YACC
     - YANG
     - YC
     - YIN
     - XVC
     - FLO
     - XEM
     - ARCH
     - HUGE
     - GRC
     - IOC
     - INDEX
     - ETH
     - SC
     - BCY
     - EXP
     - FCT
     - BITUSD
     - BITCNY
     - RADS
     - AMP
     - VOX
     - DCR
     - LSK
     - DAO
     - LBC
     - STEEM
     - SBD
     - ETC
     - REP
     - ARDR
     - ZEC
     - STRAT
     - NXC
     - PASC
     - GNT
     - GNO
     - BCH
     - ZRX
     - CVC
     - OMG
     - GAS
     - STORJ
     - EOS
     - USDC
     - SNT
     - KNC
     - BAT
     - LOOM
     - QTUM
     - BNT
     - MANA
     - FOAM
     - BCHABC
     - BCHSV
     - NMR
     - POLY
     - LPT
     - ATOM
     - GRIN
     - TRX
     - ETHBNT
     - BTT
     - WIN
     - BEAR
     - BULL
     - BUSD
     - DAI
     - LINK
     - MKR
     - PAX
     - TRXBEAR
     - TRXBULL
     - ETHBEAR
     - ETHBULL
     - SNX
     - XTZ
     - USDJ
     - MATIC
     - BCHBEAR
     - BCHBULL
     - BSVBEAR
     - BSVBULL
     - BNB
     - AVA
     - JST
     - BVOL
     - IBVOL
     - NEO
     - SWFTC
     - STPT
     - FXC
     - XRPBULL
     - XRPBEAR
     - EOSBULL
     - EOSBEAR
     - LINKBULL
     - LINKBEAR
     - CHR
     - MDT
     - BCHC
     - COMP
     - WRX
     - CUSDT
     - XFIL
     - LEND
     - REN
     - LRC
     - BAL
     - STAKE
     - BZRX
     - SXP
     - MTA
     - YFI
     - TRUMPWIN
     - TRUMPLOSE
     - DEC
     - PLT
     - UMA
     - KTON
     - RING
     - SWAP
     - TEND
     - TRADE
     - GEEQ
     - BAND
     - DIA
     - DOS
     - ZAP
     - TRB
     - SBREE
     - DEXT
     - MCB
     - PERX
     - DOT
     - CRV
     - XDOT
     - OCEAN
     - DMG
     - OM
     - BLY
     - OPT
     - PRQ
     - SWINGBY
     - FUND
     - RSR
     - WNXM
     - FCT2
     - SUSHI
     - YFII
     - YFV
     - YFL
     - TAI
     - PEARL
     - ANK
     - JFI
     - CRT
     - SAL
     - CORN
     - SWRV
     - FSW
     - CREAM

